#!/usr/bin/env bash
# .env → arduino/05_groq_voice_chat/secrets.h
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"
OUT="$ROOT/arduino/05_groq_voice_chat/secrets.h"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: $ENV_FILE not found. Copy .env.example and fill in values."
  exit 1
fi

# shellcheck disable=SC1090
source "$ENV_FILE"

# WIFI_* optional: empty → device uses SoftAP portal (Talkbot-Setup)
KEY="${GROQ_API:-${GROQ_API_KEY:-}}"
if [[ -z "$KEY" ]]; then
  echo "ERROR: Set GROQ_API in .env"
  exit 1
fi

escape() {
  python3 -c 'import sys; print(sys.argv[1].replace("\\", "\\\\").replace("\"", "\\\""))' "$1"
}

SSID_ESC=$(escape "${WIFI_SSID:-}")
PASS_ESC=$(escape "${WIFI_PASSWORD:-}")
KEY_ESC=$(escape "$KEY")

GOOGLE_KEY="${GOOGLE_API:-}"
GOOGLE_KEY_ESC=$(escape "$GOOGLE_KEY")

# Control panel base URL (Cloudflare Workers). Floor QR = CONTROL_PANEL_URL/?d=&t=
PANEL_URL="${CONTROL_PANEL_URL:-https://talkbot-control-panel.nine-raptorex.workers.dev}"
PANEL_URL="${PANEL_URL%/}"
PANEL_ESC=$(escape "$PANEL_URL")

cat > "$OUT" <<EOF
#pragma once
// Auto-generated by scripts/sync_secrets.sh — do not commit

#define WIFI_SSID "$SSID_ESC"
#define WIFI_PASSWORD "$PASS_ESC"
#define GROQ_API_KEY "$KEY_ESC"
#define GOOGLE_API_KEY "$GOOGLE_KEY_ESC"
#define CONTROL_PANEL_URL "$PANEL_ESC"
EOF

echo "Wrote $OUT"
echo "CONTROL_PANEL_URL=$PANEL_URL"
if [[ -z "${WIFI_SSID:-}" ]]; then
  echo "Note: WIFI_SSID empty — use SoftAP Talkbot-Setup / http://192.168.4.1"
fi
